### ISSUE TITLE
Unable to use 2.1.0 with the latest version of django-treebeard

### ISSUE THREAD

**Issue by pecheneff** [django-cms/djangocms-history#45]
Since django-treebeard's version is pinned we can't update djangocms-history to the latest version. We have django-treebeard==4.6.1 in the project.

**Comment by fsbraun** [comment]
@pecheneff This project is in urgent need of some love. Can I interest you in creating a PR that does two things:

1. Update the test suite to run on django 3.2, 4.0 and 4.1 and django-cms up to 3.11
2. Update the `settings.py` and remove the treebeard dependency. AFAIK this package does only indirectly depend on treebeard (through django-cms)

Django CMS is a [community-driven project](https://django-cmsworkspace.slack.com/archives/CQ97U91UM) and needs support by its users. 

Let me know if you need any help with that! Your contribution would be greatly appreciated!

**Comment by fsbraun** [comment]
Fixed with 2.2.0
