### ISSUE TITLE
BUG: Cannot undo/redo plugin djangocms-picture.

### ISSUE THREAD

**Issue by svandeneertwegh** [django-cms/djangocms-history#52]
I added a image in my structure plugins.

When i click undo/redo i get the following error:

`  File "/Users/stefan/projects/djcms3/djangocms_history/models.py", line 395, in _object_version_data_hook
    return ArchivedPlugin(**data)
TypeError: <lambda>() got an unexpected keyword argument 'model'`

**Comment by fsbraun** [comment]
Do you have a traceback?

**Comment by svandeneertwegh** [comment]
Yes. Here https://elmah.io/tools/stack-trace-formatter/5c706a8685c0439d93f5e045327d3d8c/
